name: Test

on:
  push:
    branches-ignore:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [21]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}, ${{ matrix.mode }}
    timeout-minutes: 180

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: ${{ matrix.java }}
        cache: maven
        check-latest: true

    - name: Run
      run: mvn clean install -B --file pom.xml  -DskipTests

